server:
  servlet:
    context-path: /attendancesystemqa/api

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tuition_attendance_qa?createDatabaseIfNotExist=true&serverTimezone=UTC}

logging:
  level:
    com.tuition.attendance: INFO
