server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /tutionattendancesystem
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tuition_attendance_prod?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:3br15EE003}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.tuition.attendance: WARN

app:
  profile-name: prod
  cors:
    allowed-origins:
      - ${FRONTEND_ORIGIN:http://35.154.0.23}
      - ${FACE_SERVICE_ORIGIN:http://35.154.0.23}
